# Site settings
 name: RDF platform
 group: EMBL-EBI SPOT
 email: noreply@ebi.ac.uk
 domain: /
 baseurl: ../
 permalink: pretty

 # Add custom CSS / JS here
 # custom_css:
 # - "{{site.baseurl}}/static/css/YOUR-CSS-COMPONENTS.css"
 # - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
 #custom_js:
 # - "{{site.baseurl}}/static/js/services.js"
 # - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"

 ga_code: 'UA-XXXXX-X'

 # Build settings
 markdown: kramdown

 kramdown:
   parse_block_html: true
