# Site settings
name: RDF platform 
group: EMBL-EBI SPOT 
email: noreply@ebi.ac.uk
domain: //ebispot.github.io
baseurl: /RDF-platform 
permalink: pretty

# Add custom CSS / JS here
# custom_css:
# - "{{site.baseurl}}/static/css/YOUR-CSS-COMPONENTS.css"
# - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
#custom_js:
# - "https://ebispot.github.io/RDF-platform/static/js/services.js"
# - "{{site.baseurl}}/static/js/services.js"
# - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"

Services.javascript:
 - "https://ebispot.github.io/RDF-platform/static/js/services.js"

ga_code: 'UA-XXXXX-X'

# Build settings
markdown: kramdown
